package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Vibrant Palette - Light Source
val VibrantPrimaryLight = Color(0xFF006874)
val VibrantOnPrimaryLight = Color(0xFFFFFFFF)
val VibrantPrimaryContainerLight = Color(0xFFD0E4FF)
val VibrantOnPrimaryContainerLight = Color(0xFF001E2E)
val VibrantSecondaryLight = Color(0xFF4A6267)
val VibrantOnSecondaryLight = Color(0xFFFFFFFF)
val VibrantSecondaryContainerLight = Color(0xFFF0F4F8)
val VibrantOnSecondaryContainerLight = Color(0xFF051F23)
val VibrantTertiaryLight = Color(0xFF005234)
val VibrantTertiaryContainerLight = Color(0xFFE6FFF5)
val VibrantOnTertiaryContainerLight = Color(0xFF002112)
val VibrantErrorLight = Color(0xFFBA1A1A)
val VibrantErrorContainerLight = Color(0xFFFFF0EF)
val VibrantOnErrorContainerLight = Color(0xFF93000A)
val VibrantBackgroundLight = Color(0xFFFBFCFD)
val VibrantOnBackgroundLight = Color(0xFF191C1E)
val VibrantSurfaceLight = Color(0xFFFFFFFF)
val VibrantOnSurfaceLight = Color(0xFF191C1E)
val VibrantSurfaceVariantLight = Color(0xFFDDE3EA)
val VibrantOnSurfaceVariantLight = Color(0xFF41484D)
val VibrantOutlineLight = Color(0xFF71787D)
val VibrantOutlineVariantLight = Color(0xFFC1C7CE)

// Vibrant Palette - Dark Source
val VibrantPrimaryDark = Color(0xFF86D2E1)
val VibrantOnPrimaryDark = Color(0xFF00363D)
val VibrantPrimaryContainerDark = Color(0xFF004F58)
val VibrantOnPrimaryContainerDark = Color(0xFFB1ECF8)
val VibrantSecondaryDark = Color(0xFFB1CBD0)
val VibrantOnSecondaryDark = Color(0xFF1C3438)
val VibrantSecondaryContainerDark = Color(0xFF334A4F)
val VibrantOnSecondaryContainerDark = Color(0xFFCDE7EC)
val VibrantTertiaryDark = Color(0xFF67DBA2)
val VibrantTertiaryContainerDark = Color(0xFF003822)
val VibrantOnTertiaryContainerDark = Color(0xFF91F7BD)
val VibrantErrorDark = Color(0xFFFFB4AB)
val VibrantErrorContainerDark = Color(0xFF93000A)
val VibrantOnErrorContainerDark = Color(0xFFFFDAD6)
val VibrantBackgroundDark = Color(0xFF0E1416)
val VibrantOnBackgroundDark = Color(0xFFDEE3E5)
val VibrantSurfaceDark = Color(0xFF10191B)
val VibrantOnSurfaceDark = Color(0xFFDEE3E5)
val VibrantSurfaceVariantDark = Color(0xFF3F484B)
val VibrantOnSurfaceVariantDark = Color(0xFFBFC8CB)
val VibrantOutlineDark = Color(0xFF899295)
