package com.example.ui.theme

object Localization {

    private val translations = mapOf(
        "en" to mapOf(
            "app_title" to "Smart Budget Tracking",
            "dashboard" to "Dashboard",
            "transactions" to "Transactions",
            "budget" to "Budget Planning",
            "reports" to "Reports",
            "settings" to "Settings",
            "total_balance" to "Total Balance",
            "total_income" to "Total Income",
            "total_expenses" to "Total Expenses",
            "saved_amount" to "Saved Amount",
            "monthly_budget_progress" to "Monthly Budget Progress",
            "recent_transactions" to "Recent Transactions",
            "add_income" to "Add Income",
            "add_expense" to "Add Expense",
            "edit_income" to "Edit Income",
            "edit_expense" to "Edit Expense",
            "delete_item" to "Delete Item",
            "category" to "Category",
            "amount" to "Amount",
            "date" to "Date",
            "note" to "Note",
            "save" to "Save",
            "cancel" to "Cancel",
            "weekly_expense" to "Weekly Expenses Overview",
            "spend_by_category" to "Category-wise Expenses",
            "income_vs_expense" to "Income vs Expenses",
            "budget_limits" to "Budget Limits",
            "budget_warning" to "Your budget limit has been exceeded!",
            "savings_goals" to "Savings Goals",
            "add_goal" to "Add Goal",
            "goal_name" to "Goal Name",
            "target_amount" to "Target Amount",
            "target_date" to "Target Date",
            "remaining" to "remaining",
            "achieve_prediction" to "Achievement Prediction",
            "smart_budget_score" to "Smart Budget Score",
            "spending_control" to "Spending Control",
            "savings_habit" to "Savings Habit",
            "budget_discipline" to "Budget Discipline",
            "salary_detection" to "Account Link & Salary simulation",
            "connect_bank" to "Connect Mock Bank Account",
            "simulate_salary" to "Simulate Salary Deposit",
            "auto_saved_alert" to "10% auto-saved successfully!",
            "cloud_backup" to "Cloud Backup & Restore",
            "backup_now" to "Backup to Cloud",
            "restore_now" to "Restore Data",
            "pin_lock" to "PIN Security Lock",
            "biometric_login" to "Biometric Authentication",
            "language" to "App Language",
            "ai_insights" to "🤖 Smart AI Spending Analytics",
            "generate_insights" to "Analyze Spend with Gemini",
            "loading" to "Connecting to Gemini...",
            "salary_received" to "Salary received! Auto-saving custom 10% rules active",
            "search_filter" to "Search & Filter Transactions",
            "date_filter" to "Filter by Date",
            "category_filter" to "Filter by Category",
            "all" to "All",
            "salary" to "Salary",
            "business" to "Business",
            "freelancing" to "Freelancing",
            "gifts" to "Gifts",
            "other" to "Other",
            "food" to "Food",
            "transport" to "Transport",
            "shopping" to "Shopping",
            "education" to "Education",
            "bills" to "Bills",
            "healthcare" to "Healthcare",
            "entertainment" to "Entertainment",
            "rent" to "Rent",
            "others" to "Others",
            "export_report" to "Export Financial Reports",
            "export_csv" to "Share Financial Report (CSV)",
            "lock_title" to "Enter PIN to Unlock",
            "lock_sub" to "Please authenticate to access your financial wallet",
            "invalid_pin" to "Invalid PIN, please try again",
            "register_pin" to "Register Secure Profile PIN",
            "notifications_title" to "System Notifications & Reminders",
            "no_transactions" to "No transactions found",
            "no_notifications" to "No new alerts",
            "success_backup" to "Data successfully backed up to simulated Cloud Storage",
            "success_restore" to "Data successfully synchronized and restored"
        ),
        "ta" to mapOf(
            "app_title" to "ஸ்மார்ட் பட்ஜெட் டிராக்கிங்",
            "dashboard" to "டாஷ்போர்டு",
            "transactions" to "பரிவர்த்தனைகள்",
            "budget" to "பட்ஜெட் திட்டமிடல்",
            "reports" to "அறிக்கைகள்",
            "settings" to "அமைப்புகள்",
            "total_balance" to "மொத்த இருப்பு",
            "total_income" to "மொத்த வருமானம்",
            "total_expenses" to "மொத்த செலவுகள்",
            "saved_amount" to "சேமிக்கப்பட்ட தொகை",
            "monthly_budget_progress" to "மாதாந்திர பட்ஜெட் முன்னேற்றம்",
            "recent_transactions" to "சமீபத்திய பரிவர்த்தனைகள்",
            "add_income" to "வருமானம் சேர்க்க",
            "add_expense" to "செலவு சேர்க்க",
            "edit_income" to "வருமானம் திருத்துக",
            "edit_expense" to "செலவு திருத்துக",
            "delete_item" to "நீக்க",
            "category" to "வகை",
            "amount" to "தொகை",
            "date" to "தேதி",
            "note" to "குறிப்பு",
            "save" to "சேமி",
            "cancel" to "ரத்து செய்",
            "weekly_expense" to "வாராந்திர செலவு மேலோட்டம்",
            "spend_by_category" to "வகை வாரியான செலவுகள்",
            "income_vs_expense" to "வருவாய் vs செலவு",
            "budget_limits" to "பட்ஜெட் வரம்புகள்",
            "budget_warning" to "பட்ஜெட் வரம்பு கடந்துவிட்டது!",
            "savings_goals" to "சேமிப்பு இலக்குகள்",
            "add_goal" to "இலக்கு சேர்க்க",
            "goal_name" to "இலக்கின் பெயர்",
            "target_amount" to "இலக்கு தொகை",
            "target_date" to "இலக்கு தேதி",
            "remaining" to "மீதமுள்ளது",
            "achieve_prediction" to "முடிவடையும் கணிப்பு",
            "smart_budget_score" to "ஸ்மார்ட் பட்ஜெட் மதிப்பெண்",
            "spending_control" to "செலவு கட்டுப்பாடு",
            "savings_habit" to "சேமிப்பு பழக்கம்",
            "budget_discipline" to "பட்ஜெட் கட்டுப்பாடு",
            "salary_detection" to "வங்கி இணைப்பு & சம்பளம் உருவகப்படுத்துதல்",
            "connect_bank" to "போலி வங்கி கணக்கை இணைக்கவும்",
            "simulate_salary" to "சம்பள கடனை உருவகப்படுத்துக",
            "auto_saved_alert" to "10% தானியங்கி சேமிப்பு வெற்றி அடைந்தது!",
            "cloud_backup" to "கிளவுட் காப்புப் பிரதி (Cloud Backup)",
            "backup_now" to "கிளவுட்டில் சேமி",
            "restore_now" to "தரவை மீட்டெடு",
            "pin_lock" to "பாதுகாப்பு பின் பூட்டு",
            "biometric_login" to "பயோமெட்ரிக் அங்கீகாரம்",
            "language" to "பயன்பாட்டு மொழி",
            "ai_insights" to "🤖 ஸ்மார்ட் AI செலவு பகுப்பாய்வு",
            "generate_insights" to "Gemini மூலம் பகுப்பாய்வு செய்க",
            "loading" to "Gemini உடன் இணைக்கிறது...",
            "salary_received" to "சம்பளம் பெறப்பட்டது! 10% தானியங்கி விதிகள் செயலில் உள்ளன",
            "search_filter" to "பரிவர்த்தனைகளை தேடி வடிகட்டிடுங்க",
            "date_filter" to "தேதி வாரியாக வடிகட்டு",
            "category_filter" to "வகை வாரியாக வடிகட்டு",
            "all" to "அனைத்தும்",
            "salary" to "சம்பளம்",
            "business" to "வணிகம்",
            "freelancing" to "சுயதொழில்",
            "gifts" to "பரிசுகள்",
            "other" to "மற்றவை",
            "food" to "உணவு",
            "transport" to "போக்குவரத்து",
            "shopping" to "ஷாப்பிங்",
            "education" to "கல்வி",
            "bills" to "கட்டணங்கள்",
            "healthcare" to "மருத்துவம்",
            "entertainment" to "பொழுதுபோக்கு",
            "rent" to "வாடகை",
            "others" to "இதர செலவுகள்",
            "export_report" to "அறிக்கைகளைப் பதிவிறக்குக",
            "export_csv" to "நிதி அறிக்கையினைப் பகிர்க (CSV)",
            "lock_title" to "திறக்க PIN குறியீட்டை உள்ளிடவும்",
            "lock_sub" to "பயன்பாட்டை அணுக உங்களை அங்கீகரிக்கவும்",
            "invalid_pin" to "தவறான PIN குறியீடு, மீண்டும் முயற்சிக்கவும்",
            "register_pin" to "பாதுகாப்பான PIN குறியீட்டை பதிவுசெய்யவும்",
            "notifications_title" to "அறிவிப்புகள் மற்றும் நினைவூட்டல்கள்",
            "no_transactions" to "பரிவர்த்தனைகள் எதுவும் இல்லை",
            "no_notifications" to "புதிய விழிப்பூட்டல்கள் இல்லை",
            "success_backup" to "போலி கிளவுட் தற்காலிக சேமிப்பில் வெற்றிகரமாக காப்புப் பிரதி எடுக்கப்பட்டது",
            "success_restore" to "தரவு வெற்றிகரமாக ஒத்திசைக்கப்பட்டு மீட்டெடுக்கப்பட்டது"
        ),
        "si" to mapOf(
            "app_title" to "ස්මාර්ට් අයවැය කළමනාකරණය",
            "dashboard" to "ප්‍රධාන පුවරුව",
            "transactions" to "ගනුදෙනු ලැයිස්තුව",
            "budget" to "අයවැය සැලසුම්කරණය",
            "reports" to "වාර්තා",
            "settings" to "සැකසුම්",
            "total_balance" to "මුළු ශේෂය",
            "total_income" to "මුළු ආදායම",
            "total_expenses" to "මුළු වියදම්",
            "saved_amount" to "ඉතුරුම් මුදල",
            "monthly_budget_progress" to "මාසික අයවැය ප්‍රගතිය",
            "recent_transactions" to "මෑත කාලීන ගනුදෙනු",
            "add_income" to "ආදායමක් එක් කරන්න",
            "add_expense" to "වියදමක් එක් කරන්න",
            "edit_income" to "ආදායම සංස්කරණය කරන්න",
            "edit_expense" to "වියදම සංස්කරණය කරන්න",
            "delete_item" to "මකන්න",
            "category" to "වර්ගය",
            "amount" to "මුදල",
            "date" to "දිනය",
            "note" to "සටහන",
            "save" to "සුරකින්න",
            "cancel" to "අවලංගු කරන්න",
            "weekly_expense" to "සතිපතා වියදම් දළ විශ්ලේෂණය",
            "spend_by_category" to "කාණ්ඩ අනුව වියදම්",
            "income_vs_expense" to "ආදායම් සහ වියදම් වෙනස",
            "budget_limits" to "අයවැය සීමාවන්",
            "budget_warning" to "ඔබගේ අයවැය සීමාව ඉක්මවා ඇත!",
            "savings_goals" to "ඉතුරුම් ඉලක්ක",
            "add_goal" to "ඉලක්කයක් එක් කරන්න",
            "goal_name" to "ඉලක්කයේ නම",
            "target_amount" to "අවශ්‍ය මුදල",
            "target_date" to "අවසාන දිනය",
            "remaining" to "ඉතිරිව ඇත",
            "achieve_prediction" to "ළඟා වීමේ පුරෝකථනය",
            "smart_budget_score" to "ස්මාර්ට් අයවැය ලකුණු",
            "spending_control" to "වියදම් පාලනය",
            "savings_habit" to "ඉතිරි කිරීමේ පුරුද්ද",
            "budget_discipline" to "අයවැය විනය",
            "salary_detection" to "බැංකු සම්බන්ධතාවය සහ වැටුප් සිමියුලේෂන්",
            "connect_bank" to "බැංකු ගිණුම සම්බන්ධ කරන්න",
            "simulate_salary" to "වැටුප් ලැබීම සිමියුලේට් කරන්න",
            "auto_saved_alert" to "10% ස්වයංක්‍රීයව ඉතිරි කරන ලදී!",
            "cloud_backup" to "වලාකුළු උපස්ථය (Cloud Backup)",
            "backup_now" to "ක්ලවුඩ් වෙත උපස්ථ කරන්න",
            "restore_now" to "දත්ත නැවත ලබා ගන්න",
            "pin_lock" to "PIN ආරක්ෂක අගුල",
            "biometric_login" to "ජෛවමිතික සත්‍යාපනය",
            "language" to "භාෂාව",
            "ai_insights" to "🤖 ස්මාර්ට් AI වියදම් විශ්ලේෂණය",
            "generate_insights" to "Gemini හරහා විශ්ලේෂණය කරන්න",
            "loading" to "Gemini සම්බන්ධ වෙමින් පවතී...",
            "salary_received" to "වැටුප ලැබුණි! 10% ස්වයංක්‍රීය ඉතිරි කිරීමේ රීතිය සක්‍රීයයි",
            "search_filter" to "ගනුදෙනු සොයන්න සහ පෙරන්න",
            "date_filter" to "දිනය අනුව පෙරන්න",
            "category_filter" to "වර්ගය අනුව පෙරන්න",
            "all" to "සියල්ල",
            "salary" to "වැටුප්",
            "business" to "ව්‍යාපාර",
            "freelancing" to "නිදහස් සේවා",
            "gifts" to "ත්‍යාග",
            "other" to "වෙනත්",
            "food" to "ආහාර",
            "transport" to "ප්‍රවාහන",
            "shopping" to "සාප්පු සවාරි",
            "education" to "අධ්‍යාපනය",
            "bills" to "බිල්පත්",
            "healthcare" to "සෞඛ්‍යය",
            "entertainment" to "විනෝදාස්වාදය",
            "rent" to "ගෙවල් කුලී",
            "others" to "වෙනත් වියදම්",
            "export_report" to "වාර්තා බාගත කරන්න",
            "export_csv" to "මූල්‍ය වාර්තාව බෙදා ගන්න (CSV)",
            "lock_title" to "ඇතුල් වීමට PIN අංකය ඇතුළත් කරන්න",
            "lock_sub" to "යෙදුමට පිවිසීමට ඔබගේ අනන්‍යතාවය තහවුරු කරන්න",
            "invalid_pin" to "වැරදි PIN අංකයකි, නැවත උත්සාහ කරන්න",
            "register_pin" to "නව PIN අංකයක් ලියාපදිංචි කරන්න",
            "notifications_title" to "පද්ධති දැනුම්දීම්",
            "no_transactions" to "කිසිදු ගනුදෙනුවක් සොයාගත නොහැකි විය",
            "no_notifications" to "අලුත් දැනුම්දීම් නොමැත",
            "success_backup" to "දත්ත සාර්ථකව වලාකුළු උපස්ථයට යවන ලදී",
            "success_restore" to "දත්ත සාර්ථකව සමමුහුර්ත කර නැවත ලබා ගන්නා ලදී"
        )
    )

    fun getString(key: String, languageCode: String): String {
        return translations[languageCode]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
